//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppBusStation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bus_stationEntities : DbContext
    {
        public bus_stationEntities()
            : base("name=bus_stationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bus> bus { get; set; }
        public virtual DbSet<buses> buses { get; set; }
        public virtual DbSet<flight> flight { get; set; }
        public virtual DbSet<route> route { get; set; }
        public virtual DbSet<stopping> stopping { get; set; }
    }
}
