//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppBusStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buses
    {
        public int f_ID_stopping { get; set; }
        public string f_stop_name { get; set; }
        public System.DateTime f_arrival_time { get; set; }
    }
}
