//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppBusStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public route()
        {
            this.flight = new HashSet<flight>();
        }
    
        public int ID_route { get; set; }
        public string destination { get; set; }
        public System.DateTime departure_time { get; set; }
        public int route_number { get; set; }
        public System.DateTime days_of_movement { get; set; }
        public string distance { get; set; }
        public decimal ticket_price { get; set; }
        public int ID_stopping { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flight> flight { get; set; }
        public virtual stopping stopping { get; set; }
    }
}
